"""add World.custom_theme

Revision ID: 15432da9a62b
Revises: 90fca3cf3685
Create Date: 2026-05-18 22:16:02.157429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15432da9a62b'
down_revision = '90fca3cf3685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.drop_column('custom_theme')

    # ### end Alembic commands ###
