"""add World.setting

Revision ID: 7d67e36b76f8
Revises: af8e645135d9
Create Date: 2026-05-18 18:35:36.520384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d67e36b76f8'
down_revision = 'af8e645135d9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('setting', sa.String(length=32), nullable=False, server_default='default')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.drop_column('setting')

    # ### end Alembic commands ###
