"""add Article.search_vector + GIN index

Revision ID: 90fca3cf3685
Revises: 9940114510f8
Create Date: 2026-05-18 21:52:00.884173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90fca3cf3685'
down_revision = '9940114510f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(content_md, '')), 'C')", persisted=True), nullable=True))
        batch_op.create_index('ix_articles_search', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_search', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
