"""add ArticleVersion + last_auto_version_at

Revision ID: 91dde3e12bc6
Revises: 7d67e36b76f8
Create Date: 2026-05-18 19:24:19.745289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91dde3e12bc6'
down_revision = '7d67e36b76f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('article_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('field_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('auto', 'manual')", name='ck_article_versions_kind'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_versions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_versions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('last_auto_version_at', sa.DateTime(timezone=True),
                      nullable=False, server_default=sa.func.now())
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('last_auto_version_at')

    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_versions_article_id'))

    op.drop_table('article_versions')
    # ### end Alembic commands ###
